/**
 * Build script to generate React Native icon components from SVG files
 *
 * Steps:
 * 1. Read SVG files from public/normal/category folders
 * 2. Extract path data from each SVG
 * 3. Generate component code with TypeScript definitions
 */

import * as fs from 'fs';
import * as path from 'path';

const PUBLIC_DIR = path.join(__dirname, '../../../public/normal');
const OUTPUT_DIR = path.join(__dirname, '../src/generated');

interface IconMetadata {
  name: string;
  path: string;
}

// Repository structure:
// public/normal/
//   ├── arrows/
//   │   ├── arrow-down.svg
//   │   └── arrow-up.svg
//   ├── buildings/
//   │   └── building.svg
//   └── ...

// Reverse lookup: filename without extension → { category, iconName }
const filenameMap = new Map<string, { category: string; name: string }>();

// Build the filename to category map
function buildFilenameMap() {
  const categories = fs.readdirSync(PUBLIC_DIR);

  categories.forEach(category => {
    const categoryPath = path.join(PUBLIC_DIR, category);
    if (!fs.statSync(categoryPath).isDirectory()) {
      return;
    }

    const files = fs.readdirSync(categoryPath);

    files.forEach(filename => {
      if (!filename.endsWith('.svg')) {
        return;
      }

      const nameWithoutExt = filename.slice(0, -4); // Remove ".svg"
      filenameMap.set(filename, { category, name: nameWithoutExt });
    });
  });

  console.log(`📊 Found ${filenameMap.size} icon files across ${categories.length} categories\n`);
}

// Read and parse SVG files
function readIconFiles() {
  console.log('🔍 Reading SVG files...\n');

  const iconRegistry: Record<string, IconMetadata> = {};

  filenameMap.forEach(({ category, name }, filename) => {
    try {
      const filePath = path.join(PUBLIC_DIR, category, filename);
      const svgContent = fs.readFileSync(filePath, 'utf-8');

      // Extract path data
      const pathMatch = svgContent.match(/<path\s+([^>]*?)>/);
      if (pathMatch) {
        const dMatch = pathMatch[1].match(/d="([^"]+)"/);
        if (dMatch) {
          const pathData = dMatch[1];

          // Convert icon name to camelCase with category prefix
          // arrow-down → ArrowDown
          // user → User
          const camelCaseName = name
            .split('-')
            .map(part => part.charAt(0).toUpperCase() + part.slice(1) || part)
            .join('');

          const fullIconName = `${category}_${camelCaseName}`;

          iconRegistry[fullIconName] = {
            name: camelCaseName,
            path: pathData,
          };

          console.log(`✓ ${category}/${name} → ${fullIconName}`);
        }
      }
    } catch (error) {
      console.error(`❌ Error reading ${folderPath}:${filename}`, error);
    }
  });

  return iconRegistry;
}

// Group icons by category
function groupIconsByCategory(iconRegistry: Record<string, IconMetadata>) {
  const groups: Record<string, IconMetadata[]> = {};

  Object.entries(iconRegistry).forEach(([fullPath, icon]) => {
    const [category, name] = fullPath.split('_');

    if (!groups[category]) {
      groups[category] = [];
    }

    groups[category].push({
      ...icon,
      // Reconstruct original name without category prefix
      name: name.charAt(0).toLowerCase() + name.slice(1),
    });
  });

  return groups;
}

// Write generated index file
function writeIndex(groups: Record<string, IconMetadata[]>) {
  // Sort groups alphabetically
  const sortedGroups = Object.keys(groups).sort();

  let output = `/**
 * SVG Path Data for Rune Icons (React Native Bundle)
 *
 * This file contains all icon paths bundled for React Native.
 * Icons are organized by category and ready to import.
 *
 * @generated by scripts/build-icons.ts
 */

export interface SVGPathData {
  path: string;
  name: string;
}

`;

  sortedGroups.forEach(category => {
    const iconsInCategory = groups[category];
    output += `/** ${category} */\n\n`;
    output += `/** Number of icons: ${iconsInCategory.length} */\n`;

    iconsInCategory.forEach(icon => {
      output += `/** ${icon.name} */\n`;
      output += `export const ${icon.name}: SVGPathData = {\n`;
      output += `  name: "${icon.name}",\n`;
      output += `  path: "${icon.path}",\n`;
      output += `};\n\n`;
    });

    output += `export const ${category}: SVGPathData[] = [\n`;
    iconsInCategory.forEach(icon => {
      output += `  ${icon.name},\n`;
    });
    output += `];\n\n`;
  });

  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), output);

  console.log(`\n✨ Generated ${Object.keys(groups).length} categories with ${Object.values(groups).flat().length} icon paths`);
}

// Main execution
function main() {
  console.log('🚀 Building runeicons-react-native package...\n');

  const startTime = Date.now();

  if (!fs.existsSync(PUBLIC_DIR)) {
    console.error(`❌ Public directory not found: ${PUBLIC_DIR}`);
    process.exit(1);
  }

  buildFilenameMap();
  const iconRegistry = readIconFiles();
  const groupedIcons = groupIconsByCategory(iconRegistry);
  writeIndex(groupedIcons);

  console.log(`\n✅ Complete! Generated files saved to:\n   ${OUTPUT_DIR}/index.ts\n`);

  const duration = ((Date.now() - startTime) / 1000).toFixed(2);
  console.log(`⏱️  Done in ${duration}s`);
}

main();